language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
  
  
script: 
  - mvn install -f terasoluna-tourreservation-parent/pom.xml
  - mvn install -f terasoluna-tourreservation-env/pom.xml
  - mvn install -f terasoluna-tourreservation-domain/pom.xml -Dmaven.test.skip=true
  - mvn install -f terasoluna-tourreservation-web/pom.xml